# Generated by Django 4.1.5 on 2023-02-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_name", models.CharField(max_length=255)),
                ("data_name", models.CharField(max_length=255)),
                ("data", models.JSONField(default="{}")),
            ],
            options={
                "db_table": "report_data",
            },
        ),
    ]
