# Generated by Django 4.1.5 on 2023-02-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="data",
            field=models.JSONField(default=""),
        ),
    ]
